name: Step 9, Complete Quest - Code Review

on:
  workflow_dispatch:
  issues:
    types: [opened]

permissions:
  contents: write
  issues: write

jobs:
  update_step_on_complete_quest:
    if: |
      github.event.issue.title == 'Quest: I want to automate code reviews'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update to step 9
        uses: skills/action-update-step@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 9
          to_step: 10

      - name: Comment and close issue
        uses: peter-evans/close-issue@v3
        with:
            comment: |
                ðŸŽ‰ Congratulations! You've completed the Code Review quest. Your progress has been updated and you can now continue to the next step.
    
                ðŸ‘‰ [Go to the main README to continue](../README.md)